"""initial

Revision ID: adc071621489
Revises: 
Create Date: 2026-05-10 00:18:08.294106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adc071621489'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('tour_date', sa.Date(), nullable=True),
    sa.Column('tour_duration_hours', sa.Float(), nullable=True),
    sa.Column('tour_duration_source', sa.String(), nullable=True),
    sa.Column('generation_timestamp', sa.DateTime(), nullable=True),
    sa.Column('gpx_file', sa.String(), nullable=True),
    sa.Column('total_distance_km', sa.Float(), nullable=True),
    sa.Column('elevation_gain_m', sa.Float(), nullable=True),
    sa.Column('elevation_loss_m', sa.Float(), nullable=True),
    sa.Column('image_count', sa.Integer(), nullable=True),
    sa.Column('markdown_content', sa.Text(), nullable=True),
    sa.Column('html_content', sa.Text(), nullable=True),
    sa.Column('markdown_path', sa.String(), nullable=True),
    sa.Column('html_path', sa.String(), nullable=True),
    sa.Column('model_used', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('revision_round', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photobooks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('tour_date', sa.Date(), nullable=True),
    sa.Column('tour_duration_hours', sa.Float(), nullable=True),
    sa.Column('tour_duration_source', sa.String(), nullable=True),
    sa.Column('generation_timestamp', sa.DateTime(), nullable=True),
    sa.Column('gpx_file', sa.String(), nullable=True),
    sa.Column('total_distance_km', sa.Float(), nullable=True),
    sa.Column('elevation_gain_m', sa.Float(), nullable=True),
    sa.Column('elevation_loss_m', sa.Float(), nullable=True),
    sa.Column('image_count', sa.Integer(), nullable=True),
    sa.Column('html_content', sa.Text(), nullable=True),
    sa.Column('html_path', sa.String(), nullable=True),
    sa.Column('model_used', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('pdf_path', sa.String(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('photobook_size', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('article_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=False),
    sa.Column('is_map', sa.Boolean(), nullable=True),
    sa.Column('is_elevation_profile', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_images_article_id'), 'article_images', ['article_id'], unique=False)
    op.create_table('photobook_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('photobook_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=False),
    sa.Column('is_map', sa.Boolean(), nullable=True),
    sa.Column('is_elevation_profile', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['photobook_id'], ['photobooks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photobook_images_photobook_id'), 'photobook_images', ['photobook_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_photobook_images_photobook_id'), table_name='photobook_images')
    op.drop_table('photobook_images')
    op.drop_index(op.f('ix_article_images_article_id'), table_name='article_images')
    op.drop_table('article_images')
    op.drop_table('photobooks')
    op.drop_table('articles')
    # ### end Alembic commands ###
